[tool.black]
skip-string-normalization = true
line-length = 88

[tool.coverage.run]
omit = [
    # omit dunder files, __init__.py, __main__.py, etc.
    "__*__.py",
    # omit the version file
    "version.py",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 3
use_parentheses = true
line_length = 88

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
