# Run this CI Workflow on merges to the `main` branch
name: Merge CI
on:
  push:
    branches:
      - main

# Security permissions (enabling write access for documentation)
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions CI

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5

      # Setup virtual environment, install dependencies
      - name: Setup Virtual Environment
        run: make init

      # Create documentation using pdoc
      - name: Create documentation
        run: make docs

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload documentation to docs folder
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          path: .
          if-no-files-found: error
          overwrite: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Run Semantic Release to get versioning and changelog
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
